<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-B3UT58U" failures="20" tests="24" name="Test" time="27.671" errors="0" timestamp="2024-12-04T13:31:23 IST">
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.075">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.113">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.083">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.143">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.148">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.118">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.136">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.158">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.148">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_deletePurchaseOrder" time="1.158">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_deletePurchaseOrder(Test_store.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_deletePurchaseOrder -->
  <testcase classname="api.tests.Test_store" name="test_getStroreInventory" time="1.158"/>
  <testcase classname="api.tests.Test_store" name="test_placeOrder" time="1.123"/>
  <testcase classname="api.tests.Test_store" name="test_placeOrder" time="1.172"/>
  <testcase classname="api.tests.Test_store" name="test_placeOrder" time="1.192"/>
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.117">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.154">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.152">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.158">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.128">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.158">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.178">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.184">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.172">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
  <testcase classname="api.tests.Test_store" name="test_purchaseOrderHistory" time="1.119">
    <failure type="java.lang.AssertionError" message="Order not found or invalid status code returned. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Order not found or invalid status code returned. expected [200] but found [404]
at api.tests.Test_store.test_purchaseOrderHistory(Test_store.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test_purchaseOrderHistory -->
</testsuite> <!-- Test -->
